// <auto-generated />
namespace EntityFrameworkExtraMile.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class InitializeEtc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitializeEtc));
        
        string IMigrationMetadata.Id
        {
            get { return "201310291956533_InitializeEtc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
